export const newline: number
export const eof: number
export const newlineEmpty: number
export const newlineBracketed: number
export const continueBody: number
export const endBody: number
export const _else: number
export const _elif: number
export const _except: number
export const _finally: number
export const ParenthesizedExpression: number
export const TupleExpression: number
export const ComprehensionExpression: number
export const ArrayExpression: number
export const ArrayComprehensionExpression: number
export const DictionaryExpression: number
export const DictionaryComprehensionExpression: number
export const SetExpression: number
export const SetComprehensionExpression: number
export const compoundStatement: number
export const printKeyword: number